#pragma once
#include "OpenSession.h"
#include "SetAdapter.h"
#include "SetCapture.h"
#include "EnumerateAdapters.h"
#include "Introspect.h"
#include "PushSpecification.h"
#include "BindHotkey.h"
#include "ClearHotkey.h"