#pragma once
#include "Session.h"
#include "ProcessTracker.h"
#include "FrameQuery.h"
#include "DynamicQuery.h"
#include "StaticQuery.h"
#include "../PresentMonAPIWrapperCommon/Exception.h"
#include "../PresentMonAPIWrapperCommon/EnumMap.h"
#include "../PresentMonAPIWrapperCommon/Introspection.h"
