#pragma once
#include "Session.h"
#include "ProcessTracker.h"
#include "FrameQuery.h"
#include "DynamicQuery.h"
#include "StaticQuery.h"
#include <IntelPresentMon/PresentMonAPIWrapperCommon/Exception.h>
#include <IntelPresentMon/PresentMonAPIWrapperCommon/EnumMap.h>
#include <IntelPresentMon/PresentMonAPIWrapperCommon/Introspection.h>
