// Copyright (C) 2024 Intel Corporation
// SPDX-License-Identifier: MIT
//
// This file originally generated by etw_list
//     parameters: --no_event_structs --provider=Intel-PresentMon
#pragma once

namespace Intel_PresentMon {

struct __declspec(uuid("{ECAA4712-4644-442F-B94C-A32F6CF8A499}")) GUID_STRUCT;
static const auto GUID = __uuidof(GUID_STRUCT);

enum class Keyword : uint64_t {
    FrameTypes = 0x1,
};

enum class Level : uint8_t {
    win_Informational = 0x4,
};

// Event descriptors:
#define EVENT_DESCRIPTOR_DECL(name_, id_, version_, channel_, level_, opcode_, task_, keyword_) struct name_ { \
    static uint16_t const Id      = id_; \
    static uint8_t  const Version = version_; \
    static uint8_t  const Channel = channel_; \
    static uint8_t  const Level   = level_; \
    static uint8_t  const Opcode  = opcode_; \
    static uint16_t const Task    = task_; \
    static Keyword  const Keyword = (Keyword) keyword_; \
}

EVENT_DESCRIPTOR_DECL(FlipFrameType_Info   , 0x0002, 0x00, 0x00, 0x04, 0x00, 0x0002, 0x0000000000000001);
EVENT_DESCRIPTOR_DECL(PresentFrameType_Info, 0x0001, 0x00, 0x00, 0x04, 0x00, 0x0001, 0x0000000000000001);

#undef EVENT_DESCRIPTOR_DECL

enum class FrameType : uint8_t {
    Unspecified = 0,
    Original = 1,
    Repeated = 2,
    Intel_XEFG = 50,
    AMD_AFMF = 100,
};

#pragma pack(push, 1)

struct FlipFrameType_Info_Props {
    uint32_t VidPnSourceId;
    uint32_t LayerIndex;
    uint64_t PresentId;
    FrameType FrameType;
};

struct PresentFrameType_Info_Props {
    uint32_t FrameId;
    FrameType FrameType;
};

#pragma pack(pop)

}
