// This file originally generated by etw_list
//     version:    development branch 1f6ac03eede3e9ab6a6bae5c6de68ad6dd75312d
//     parameters: --show=all --output=c++ --provider={3d6fa8d0-fe05-11d0-9dda-00c04fd7ba7c}
// Copyright (C) 2020-2021 Intel Corporation
// SPDX-License-Identifier: MIT
#pragma once

namespace NT_Process {

struct __declspec(uuid("{3d6fa8d0-fe05-11d0-9dda-00c04fd7ba7c}")) GUID_STRUCT;
static const auto GUID = __uuidof(GUID_STRUCT);

}
