#pragma once 
#include "acts/EnumerateAdapters.h" 
#include "acts/GetStaticCpuMetrics.h" 
#include "acts/OpenSession.h" 
#include "acts/SelectAdapter.h" 
#include "acts/SetEtwFlushPeriod.h" 
#include "acts/SetTelemetryPeriod.h" 
#include "acts/StartTracking.h" 
#include "acts/StopTracking.h" 
