BEGIN{
    FS = "\"";
    print "// WARNING: This file is automatically generated, modify IntelPresentMon\\metrics.csv instead.";
    print "//";
    print "// enum annotation (enum_name_fragment, key_name_fragment, name, short_name, description)";
    printf "#define ENUM_KEY_LIST_METRIC(X_)";
}
{
    n = split($1, a, ",")

    #printf "\n%u:%u: ", NF, n
    #for (i = 1; i <= n; ++i) printf "|%s", a[i]
    #printf("|-")
    #for (i = 2; i <= NF; ++i) printf "|%s", $i
    #printf("|\n")

    if (a[1] == "") next
    if (substr(a[1], 1, 2) == "//") next

    if (NF == 1) {
        name = a[3]
        desc = a[4]
    } else if (NF == 3) {
        name = substr(a[3], 1, length($1)-1)
        desc = $2
    }

    shortname = name
    gsub(/ /, "", shortname)
    gsub(/-/, "", shortname)

    if (shortname == "ProcessID") next
    if (shortname == "VideoBusy") next

    printf " \\\n\t\tX_(METRIC, %s, \"%s\", \"%s\", \"%s\")", substr(a[1], 11), name, shortname, desc
}
END{
    printf "\n"
}
