#pragma once
#include "../../../PresentMonAPI2/PresentMonAPI.h"

#define PREFERRED_UNIT_LIST(X_) \
		X_(PM_METRIC_GPU_MEM_USED, PM_UNIT_GIGABYTES) \
		X_(PM_METRIC_GPU_MEM_WRITE_BANDWIDTH, PM_UNIT_GIGABITS_PER_SECOND) \
		X_(PM_METRIC_GPU_MEM_READ_BANDWIDTH, PM_UNIT_GIGABITS_PER_SECOND) \
		X_(PM_METRIC_GPU_MEM_SIZE, PM_UNIT_GIGABYTES) \
		X_(PM_METRIC_GPU_MEM_MAX_BANDWIDTH, PM_UNIT_GIGABITS_PER_SECOND)
