// Copyright (C) 2017-2024 Intel Corporation
// SPDX-License-Identifier: MIT
#pragma once

#ifndef PRESENTMONPROVIDER_ASSERT
#ifdef NDEBUG
#define PRESENTMONPROVIDER_ASSERT(_C) (void) _C
#else
#define PRESENTMONPROVIDER_ASSERT assert
#endif
#endif

// Before emitting any Intel-PresentMon events, the provider needs to be initialized by calling
// PresentMonProvider_Initialize().  PresentMonProvider_Initialize() returns a context to use for
// other PresentMonPrivider calls, or nullptr if the initialization failed.
//
// Call PresentMonProvider_ShutDown() when you no longer need to generate any Intel-PresentMon
// events.  ctxt is deallocated during PresentMonProvider_ShutDown() and can no longer be used.

struct PresentMonProvider;
PresentMonProvider* PresentMonProvider_Initialize();

void PresentMonProvider_ShutDown(PresentMonProvider* ctxt);


// Once you successfully initialize the provider, you can generate the following events.
//
// Event function arguments are checked with PRESENTMONPROVIDER_ASSERT().  Each function will return
// one of the following status values:
//
//     - ERROR_SUCCESS:             The event was written successfully.
//
//     - ERROR_INVALID_HANDLE:      PresentMonProvider_Initialize() was not called or was not
//                                  successful.
//
//     - ERROR_MORE_DATA:           The ETW session buffer size is too small for the event.
//
//     - ERROR_NOT_ENOUGH_MEMORY:   Can occur when the disk IO cannot keep up with the amount of 
//                                  events being generated.
//
//     - Other return values may be returned in the event of a PresentMonProvider internal error.


// PRESENTING GENERATED FRAMES
//
// Drivers or SDKs that present generated frames other than the application-rendered frames should
// emit these events to ensure PresentMon can properly track them.
//
// For generated frames that are submitted through a standard present API, inform PresentMon what
// type of frame it is by emitting the 'PresentFrameType' event immediately before calling Present()
// for the frame, on the same thread as the Present() call.  You do not need to emit a
// 'FlipFrameType' event in this case as the flip will be detected using standard events.
//
// For generated frames that are submitted through a proprietary mechanism, emit the 'FlipFrameType'
// event as close to the flip time as possible.  'vidPnSourceId', 'layerIndex', and 'presentId'
// refer to the application's initially-presented frame and should match the values in the
// corresponding MMIOFlipMultiPlaneOverlay3 event.

enum PresentMonProvider_FrameType {
    PresentMonProvider_FrameType_Unspecified,       // Use when no other values are appropriate (file github request
                                                    // to have your technique added).
    PresentMonProvider_FrameType_Original,          // The original frame rendered by the application.
    PresentMonProvider_FrameType_Repeated,          // The frame rendered by the application is being repeated.
    PresentMonProvider_FrameType_AMD_AFMF = 100,    // Frame generated by AMD Fluid Motion Frames.
};

ULONG PresentMonProvider_PresentFrameType(PresentMonProvider* ctxt,
                                          PresentMonProvider_FrameType frameType);

ULONG PresentMonProvider_FlipFrameType(PresentMonProvider* ctxt,
                                       uint32_t vidPnSourceId,
                                       uint32_t layerIndex,
                                       uint64_t presentId,
                                       PresentMonProvider_FrameType frameType);
